id: labelAdded.mapQuest
name: GitOps.MapQuestHandler
description: Handles when "mapQUEST" label is added
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: >-
          When the label "mapQUEST" is added to an issue
          * Remove label "mapQUEST"
        if:
          - payloadType: Issues
          - labelAdded:
              label: ":world_map: mapQUEST"
        then:
          - removeLabel: ":world_map: mapQUEST"
        triggerOnOwnActions: true
      - description: >-
          When the label "mapQUEST" is added to a pull request
          * Remove label "mapQUEST"
        if:
          - payloadType: Pull_Request
          - labelAdded:
              label: ":world_map: mapQUEST"
        then:
          - removeLabel: ":world_map: mapQUEST"
        triggerOnOwnActions: true
onFailure:
onSuccess:
