id:
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    scheduledSearches:
    - description: Label doc-bug issues with okr-health (scheduled search)
      frequencies:
      - hourly:
          hour: 3
      filters:
      - isIssue
      - isOpen
      - hasLabel:
          label: doc-bug
      - isNotLabeledWith:
          label: okr-health
      actions:
      - addLabel:
          label: okr-health
          
    eventResponderTasks:
    - description: Label issues with okr-health (event-based)
      if:
      - payloadType: Issues
      - or:
        - hasLabel:
            label: doc-bug
        - titleContains:
            pattern: freshness
            isRegex: False
        - titleContains:
            pattern: out( |-)of( |-)date
            isRegex: True
      then:
      - addLabel:
          label: okr-health

    - description: Add in-pr label to issues
      if:
      - payloadType: Pull_Request
      then:
      - inPrLabel:
          label: in-pr

    - description: Label typo issues
      if:
      - payloadType: Issues
      - isAction:
          action: Opened
      - titleContains:
          pattern: (T|t)ypo
          isRegex: True
      then:
      - addLabel:
          label: doc-bug
      - addLabel:
          label: help wanted
      - addLabel:
          label: good first issue

