id: pullRequestManagement.serviceLabels
name: GitOps.PullRequestServiceLabels
description: Checks the files touched by a pull request and assigns area labels.
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description:
        if:
          - payloadType: Pull_Request

        then:
          # Framework WPF
          - if:
              - filesMatchPattern:
                  pattern: '(?i).*dotnet-desktop-guide\/framework\/wpf.*'
            then:
              - addLabels:
                  - label: 'dotnet-framework/svc'
              - addLabels:
                  - label: 'wpf/subsvc'
        triggerOnOwnActions: false

onFailure:
onSuccess:
