id: pullRequestManagement.serviceLabels
name: GitOps.PullRequestServiceLabels
description: Checks the files touched by a pull request and assigns area labels.
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Add labels to PRs that touch certain files
        if:
          - payloadType: Pull_Request
          - or:
            - isAction:
                Opened
            - isAction:
                Synchronize
          - not:
              targetsBranch:
                branch: live
        then:
          - addLabels:
            - label: 'dotnet-framework/svc'
            - label: 'wpf/subsvc'
        triggerOnOwnActions: false

onFailure:
onSuccess:
