id: pullRequestManagement.serviceLabels
name: GitOps.PullRequestServiceLabels
description: Checks the files touched by a pull request and assigns area labels.
owner:
resource: repository
disabled: false
where:
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: Label community PRs
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          - and:
              - not:
                  activitySenderHasPermission:
                    permission: Admin
              - not:
                  activitySenderHasPermission:
                    permission: Write
              - not:
                  isActivitySender:
                    user: github-actions[bot]
              - not:
                  isActivitySender:
                    user: github-actions
              - not:
                  isActivitySender:
                    user: azure-sdk
              - not:
                  isActivitySender:
                    user: dependabot
        then:
          - addLabel:
              label: community-contribution
        triggerOnOwnActions: false

onFailure:
onSuccess:
