revision: 4
schema-version: 5
owner-ms-alias: adegeo

config:
  DocMetadata:
    Headers:
      - ["---", "#### "]

    ParserRegex: "^\\* (.*): (.*)$"

    ContentUrlRegex:
     - "### Page URL\n\n(.*)"

issues:

  opened:

    # Add links to related issues if it's a doc issue
    - check:
        - type: metadata-exists
        - type: variable-exists
          name: "document_version_independent_id"
      pass:
        - link-related-issues

pull_request:

  reopened: opened

  opened:

    # Set default sprint for new PRs
    - milestone-set: "![sprint]"
  
    - check:
        - type: query
          value: "PullRequest.Base.Ref != 'live'"
      pass:
        - files-changed:
            - path: "(?i).*dotnet-desktop-guide\/framework\/wpf.*"
              run:
                - labels-add: ["dotnet-framework/svc", "wpf/subsvc"]

            - path: "(?i).*dotnet-desktop-guide\/framework\/winforms.*"
              run:
                - labels-add: ["dotnet-framework/svc", "winforms/subsvc"]

            - path: "(?i).*dotnet-desktop-guide\/net\/wpf.*"
              run:
                - labels-add: ["dotnet-desktop/svc", "wpf/subsvc"]

            - path: "(?i).*dotnet-desktop-guide\/net\/winforms.*"
              run:
                - labels-add: ["dotnet-desktop/svc", "winforms/subsvc"]

projects_v2_item:

  reordered:

    - labels-add: [":world_map: mapQUEST"]

  edited:

    - check:
        - type: query
          value: "EventPayload.changes.field_value.field_name == 'Priority' || EventPayload.changes.field_value.field_name == 'Size'"
      pass:
        - labels-add: [":world_map: mapQUEST"]
