# ms.topic: <implementation-name> version 1.0.0
items:
- name: <Suggested title>
  href: <path-template>
  required: yes
  limit: 1
- name: <Suggested title>
  href: <path-template>
  required: yes
  limit: 1
- name: <Suggested title>
  href: <path-template>
  required: No
  limit: none