# guide: upgrade-and-migration
name: Upgrade or Migration guide
items:
- name: Overview
  href: "https://review.learn.microsoft.com/help/patterns/level4/global-overview-template"
  required: yes
  limit: 1
- name: Prerequisites
  href: "https://review.learn.microsoft.com/help/patterns/level4/global-concept-template"
  required: no
  limit: 1
- name: Methods
  href: "https://review.learn.microsoft.com/help/patterns/level4/global-concept-template"
  required: no
  limit: 1
- name: Resources
  href: "https://review.learn.microsoft.com/help/patterns/level4/global-concept-template"
  required: no
  limit: 1
- name: Assessment
  href: "https://review.learn.microsoft.com/help/patterns/level4/global-concept-template"
  required: no
  limit: 1
- name: Preupgrade or premigration tasks
  href: "https://review.learn.microsoft.com/help/patterns/level4/global-how-to-template"
  required: no
  limit: 1
- name: Migration step 1...n
  href: "https://review.learn.microsoft.com/help/patterns/level4/global-how-to-template"
  required: yes
  limit: none
- name: Validation
  href: "https://review.learn.microsoft.com/help/patterns/level4/global-how-to-template"
  required: no
  limit: 1
- name: Post-upgrade or post-migration tasks
  href: "https://review.learn.microsoft.com/help/patterns/level4/global-how-to-template" 
  required: no
  limit: 1
- name: What to expect after upgrade or migration
  href: "https://review.learn.microsoft.com/help/patterns/level4/global-concept-template" 
  required: no
  limit: 1
- name: Troubleshooting
  href: "https://review.learn.microsoft.com/help/patterns/level4/global-general-troubleshoot-template"
  required: no
  limit: 1