# guide: planning
name: Plan __
items:
- name: Plan __
  items: 
  - name: Plan __
    href: "https://review.learn.microsoft.com/en-us/help/patterns/level4/global-overview-template"
    required: yes
    limit: 1
  - name: Prerequisites
    href: "https://review.learn.microsoft.com/en-us/help/patterns/level4/global-concept-template" # alternately, can use ms.topic: checklist
    required: yes
    limit: 0
  - name: Prerequisites
    href: "https://review.learn.microsoft.com/en-us/help/patterns/level4/global-checklist-template"  # alternately, can use ms.topic: concept-article
    required: no
    limit: 1
  - name: Considerations
    href: "https://review.learn.microsoft.com/en-us/help/patterns/level4/global-concept-template" # alternately, can use ms.topic: checklist
    required: yes
    limit: 1
  - name: Considerations
    href: "https://review.learn.microsoft.com/en-us/help/patterns/level4/global-checklist-template" # alternately, can use ms.topic: concept-article
    required: no
    limit: 1