# guide: waf-workload
name: Workload name documentation
items:
- name: Quick links
  href: index.yml #landing page template
  required: yes
  limit: 1
- name: Get started
  href: "help-content/patterns/level4/waf-get-started-template.md"
  required: yes
  limit: 1
- name: Design methodology
  href: "help-content/patterns/level4/waf-design-methodology-template.md"
  required: yes
  limit: 1
- name: Design principles
  href: "help-content/patterns/level4/waf-design-principles-template.md"
  required: yes
  limit: none
- name: Cross-cutting concerns
  href: "help-content/patterns/level4/waf-cross-cutting-concerns-template.md"
  required: yes
  limit: 1
- name: Architecture pattern
  href: "help-content/patterns/level4/waf-architecture-pattern-template.md"
  required: yes
  limit: 1
- name: Design areas
  href: "help-content/patterns/level4/waf-design-areas-template.md"
  required: yes
  limit: 1