items:
- name: What is /<product/> 
  href: ../templates/template-overview.md
- name: Similar /<product/> comparison  
- href: ../templates/template-product-comparison.md
- name: When to use /<product/>
- href:  ../templates/template-concept.md
- name: /<prodcut/> Set up
- href: ../templates/template-quickstart.md
- name: How to guide
  href: ../templates/template-how-to-guide.md
- name: How to guide
  href: ../templates/template-how-to-guide.md
- name: How to guide
  href: ../templates/template-how-to-guide.md
- name: How to get support
  href:  ../templates/template-concept.md