items:
- name: <Solution> overview 
  href: ../templates/template-solution-overview.md
- name: How to article
  href: ../templates/template-how-to-guide.md
- name: How to guide
  href: ../templates/template-how-to-guide.md
- name: How to guide
  href: ../templates/template-how-to-guide.md