name: "Desktop doc problem"
description: Report a problem in the WPF/Windows Forms documentation.
title: "[doc bug]: "
labels: Pri1,doc-bug
assignees:
 - adegeo
body:
  - type: markdown
    attributes:
      value: |
        ```
        ┌───────────┐
        │ IMPORTANT ├──────────────────────────┐
        └────────┬──┘ Please read the          │
                 │       following statement   │
                 └─────────────────────────────┘
        ```

        If your question is related to a specific article, **STOP**. Go back to the article page and scroll to the bottom where the GitHub section is. Use the link there to open the issue.

  - type: dropdown
    id: technology
    attributes:
      label: Technology
      description: Which desktop technology are you using?
      options:
        - WPF (Windows Presentation Foundation)
        - Windows Forms
    validations:
      required: true

  - type: checkboxes
    id: platform
    attributes:
      label: Version
      description: Which .NET version did you notice this problem with?
      options:
        - label: ".NET 5 or later (also .NET Core)"
        - label: ".NET Framework 4"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What's the problem you had with the documentation? (markdown allowed)
    validations:
      required: true
